# Remote Management Request
temoto_2/RMPRequest rmp

# Type of the requested sensor (required).
string sensor_type

# Name of the ROS package where sensor is located. (optional)
# If the package name is left undefined
# then the first known entry under the specified type is executed
string package_name

# name of the executable (optional)
# When undefined, first defined entry is used.
string executable

# Output topics. Each element is a pair of strings where the 
# first element (key) describes the type of the topic and the
# second element (value) describes the name of the topic itself.
# Key is required but if the value is left empty, a default
# topic name is used (indicated by the sensor info file)
# by the sensor manager
diagnostic_msgs/KeyValue[] output_topics

# Same idea applies here as it did with the output_topics
diagnostic_msgs/KeyValue[] input_topics

---

# Remote Management Response
temoto_2/RMPResponse rmp

# name of the package
string package_name

# name of the executable/launchable/runnable
string executable

# Actual output topics
diagnostic_msgs/KeyValue[] output_topics

diagnostic_msgs/KeyValue[] input_topics
